djangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from userextend.forms import AuthenticationNewForm

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('intro.urls')),
    path('', include('home.urls')),
    path('', include('student.urls')),
    path('', include('trainer.urls')),
    path('login/', views.LoginView.as_view(form_class=AuthenticationNewForm)),
    path('',include('django.contrib.auth.urls')),
    path('',include('userextend.urls')),
    path('', include('feedback.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# Aceasta linie de cod face parte din configurarea fisierelor statice si este
# utilizata pentru a asigura afisarea corecta a fisierlui din media

# functi static() primeste 2 args:
# setting.MEDIA_URL reprezinta url de baza pentru fisierele media
# setting.MEDIA_ROOT reprezinta folderu fizic in care fisierele media sunt stocate

# In concluzie, serverul va putea prelua fisierele media prin intermediul url specificat

home/urls.py
from django.urls import path

from home import views

urlpatterns = [
    path('', views.HomeTemplateView.as_view(), name='home-page')

]

trainer/urls.py
from django.urls import path

from trainer import views

urlpatterns = [
    path('create_trainer/', views.TrainerCreateView.as_view(), name='create-trainer'),
    path('list_of_trainers/', views.TrainerListView.as_view(), name='list-of-trainers'),
    path('update_trainer/<int:pk>/', views.TrainerUpdateView.as_view(), name='update-trainer'),
    path('delete_trainer/<int:pk>/', views.TrainerDeleteView.as_view(), name='delete-trainer'),
    path('detail_trainer/<int:pk>/', views.TrainerDetailView.as_view(), name='detail-trainer'),
]

trainer/models.py
from django.db import models


class Trainer(models.Model):
    department_options = (
        ('backend','Backend'),
        ('frontend','Frontend'),
        ('network', 'Network')
    )

    first_name=models.CharField(max_length=20)
    last_name=models.CharField(max_length=20)
    course = models.CharField(max_length=40)
    email = models.EmailField(max_length=40)
    department = models.CharField( max_length=8, choices=department_options)
    active = models.BooleanField(default=True)
    profile = models.ImageField(upload_to='profile/', null=True)


    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # pip install pillow -> este folosit pentru a va procesa imaginile

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

trainer/forms.py
from django import forms

from django.forms import Select, EmailInput, TextInput

from student.models import Student
from trainer.models import Trainer


class TrainerForm(forms.ModelForm):
    class Meta:
        model = Trainer
        fields = ['first_name', 'last_name', 'course', 'email', 'department', 'active', 'profile']

        widgets = {
            'first_name': TextInput(attrs={'class': 'form-control', 'placeholder': 'Please enter your first name'}),
            'last_name': TextInput(attrs={'class': 'form-control', 'placeholder': 'Please enter your last name'}),
            'course': TextInput(attrs={'class': 'form-control', 'placeholder': 'Please enter your course'}),
            'email': EmailInput(attrs={'class': 'form-control', 'placeholder': 'Please enter your email'}),
            'department': Select(attrs={'class': 'form-select'}),
        }

    def clean(self):

        clean_data = self.cleaned_data

        # Email Unique

        get_email = clean_data.get('email')

        check_email = Student.objects.filter(email=get_email)
        if check_email:
            msg = 'Exista adresa de email in sistem'
            self._errors['email'] = self.error_class([msg])

        return self.cleaned_data


class TrainerUpdateForm(forms.ModelForm):
    class Meta:
        model = Trainer
        fields = ['first_name', 'last_name', 'course', 'email', 'department', 'active', 'profile']

        widgets = {
            'first_name': TextInput(attrs={'class': 'form-control', 'placeholder': 'Please enter your first name'}),
            'last_name': TextInput(attrs={'class': 'form-control', 'placeholder': 'Please enter your last name'}),
            'course': TextInput(attrs={'class': 'form-control', 'placeholder': 'Please enter your course'}),
            'email': EmailInput(attrs={'class': 'form-control', 'placeholder': 'Please enter your email'}),
            'department': Select(attrs={'class': 'form-select'}),
        }

trainer/views.py
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView

from feedback.models import Feedback
from student.models import Student
from trainer.forms import TrainerForm, TrainerUpdateForm
from trainer.models import Trainer


class TrainerCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    template_name = 'trainer/create_trainer.html'
    model = Trainer
    form_class = TrainerForm
    success_url = reverse_lazy('home-page')
    permission_required = 'trainer.add_trainer'


class TrainerListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    template_name = 'trainer/list_of_trainers.html'
    model = Trainer
    context_object_name = 'all_trainers'
    permission_required = 'trainer.view_list_of_trainer'


class TrainerUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    template_name = 'trainer/update_trainer.html'
    model = Trainer
    form_class = TrainerUpdateForm
    success_url = reverse_lazy('list-of-trainers')
    success_message = "{f_name} {l_name}"
    permission_required = 'trainer.view_trainer'

    def get_success_message(self, clean_data):
        return self.success_message.format(f_name=self.object.first_name, l_name=self.object.last_name)


class TrainerDeleteView(LoginRequiredMixin,PermissionRequiredMixin, DeleteView):
    template_name = 'trainer/delete_trainer.html'
    model = Trainer
    success_url = reverse_lazy('list-of-trainers')
    permission_required ='trainer.delete_trainer'


class TrainerDetailView(LoginRequiredMixin,PermissionRequiredMixin, DetailView):
    template_name = 'trainer/details_trainer.html'
    model = Trainer
    permission_required = 'trainer.view_trainer'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)  # se poate regasi si ca data = super().get_context_data(**kwargs)
        now = datetime.now()  # preluam data si ora curenta
        context[
            'current_datetime'] = now  # adaugam in dict context, cheia current_datetime pt a afisa data si ora curenta

        current_trainer_id = self.kwargs["pk"]  # Accesam id-ul trainerului selectat

        students_current = Student.objects.filter(
            trainer_id=current_trainer_id)  # realizam un query prin care luam toti studentii asignati trainerului selectat
        context[
            'students'] = students_current  # adaugam in dict context, cheia students pt a afisa o tabela cu studentii trainerului

        feedback_current = Feedback.objects.filter(trainer_id=current_trainer_id)
        context['feedbacks'] = feedback_current

        return context

    # Get Context Data(get_context_data) este o metoda folosita in clasele de View-uri(ListView, TemplateView, UpdateView, etc)
    # este utilitaza pentru a returna sau pentru a construi si a retuna un dictionar de date de context care vor fi afisate in paginile de HTML

templates/trainer/create_trainer.html
{% extends 'base.html' %}

{% block title %} Create a new trainer {% endblock %}

{% block content %}


    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <br><br>
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Create a new Trainer</h3>
                    </div>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="card-body">
                            {{ form.as_p }}
                        </div>

                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-outline-success">Add a new Trainer</button>
                            <a href="#" class="btn btn-outline-secondary">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/trainer/delete_trainer.html
{% extends 'base.html' %}

{% block title %} Delete - {{ trainer }} {% endblock %}

{% block content %}
    <div class = 'container-fluid'>
        <div class = 'row'>
            <div class = 'col-md-6 offset-md-3'>
                <br><br><br>
                <div class = 'card'>
                    <div class = 'card-header'>
                        <h3 class = 'text-center'> Delete - {{ trainer }}</h3>
                    </div>
                    <form method="post">
                        {% csrf_token %}
                    <div class = 'card-body'>
                        <p> Are you sure you want to delete {{ trainer }}</p>
                    </div>
                    <div class = 'card-footer'>
                        <button type="submit" class = 'btn btn-outline-danger'>Delete</button>
                        <a href = '{% url 'list-of-trainers' %}' class = 'btn btn-outline-secondary'>No</a>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/trainer/details_trainer.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Detail Trainer - {{ trainer }}{% endblock %}

{% block content %}

    <div class='container-fluid'>
        <div class='row'>
            <div class='col-md-6 offset-md-3'>
                <br><br><br>

                {# Trainer Details #}
                <div class='card text-center'>
                    <div class='card-header'>
                        {% if trainer.profile %}
                            <img src="{{ trainer.profile.url }}" style='width: 60px; height: 70px'
                                 alt="No Image Found">
                        {% else %}
                            {% if trainer.gender == "male" %}
                                <img src="{% static 'images/image_trainer.png' %}" alt="No Image"
                                     style='width: 60px; height: 70px'>
                            {% else %}
                                <img src="{% static 'images/image_trainer.png' %}" alt="No Image"
                                     style='width: 60px; height: 70px'>
                            {% endif %}
                        {% endif %}
                    </div>
                    <div class='card-body'>
                        <h5 class='card-title'>{{ trainer }}</h5>
                        <p class='card-text '>
                        <p>{{ current_datetime|date:"H:i:s d-m-Y  " }}</p>
                        <Strong>Email:</Strong> {{ trainer.email }}
                        <br>
                        <Strong>Departament:</Strong> {{ trainer.department.upper }}
                        <br>
                        <Strong>Course:</Strong> {{ trainer.course }}
                    </p>
                    <a href="{% url 'list-of-trainers' %}" class="btn btn-primary">Cancel</a>
                </div>
                <div class='card-footer text-body-secondary'>
                    Created at: {{ trainer.created_at|date:'d-m-Y H:i:s' }} / Updated
                    at: {{ trainer.updated_at|date:'d-m-Y H:i:s' }}
                </div>
            </div>
            <br><br>
            {# Student List    #}
            <div class="card">
                <div class="card-header">
                    <h3 class="text-center">List of Students</h3>
                </div>
                <div class="card-body">
                    {% if students %}
                        <table class="table">
                            <thead>
                            <tr>
                                <th class="text-center">First name</th>
                                <th class="text-center">Last name</th>
                                <th class="text-center">Email</th>
                                <th class="text-center">Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for student in students %}
                                <tr>
                                    <td class="text-center">{{ student.first_name }}</td>
                                    <td class="text-center">{{ student.last_name }}</td>
                                    <td class="text-center">{{ student.email }}</td>
                                    <td class="text-center"><a href="{% url 'update-student' student.id %}"
                                                               class="btn btn-outline-secondary">Update</a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        <h3 class="text-center">No Students</h3>
                    {% endif %}
                </div>
            </div>
        </div>
        <br><br>
        {# Feedback List    #}
        <div class="col-md-8 offset-md-2 pb-2">
            <br><br>
            <div class="card ">
                <div class="card-header">
                    <h3 class="text-center">List of Feedbacks</h3>
                </div>
                <div class="card-body">
                    {% if feedbacks %}
                        <table class="table">
                            <thead>
                            <tr>
                                <th class="text-start">First name</th>
                                <th class="text-start">Last name</th>
                                <th class="text-start">Email</th>
                                <th class="text-start">Message</th>
                                <th class="text-start">Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for feedback in feedbacks %}
                                <tr>
                                    <td class="text-start">{{ feedback.first_name }}</td>
                                    <td class="text-start">{{ feedback.last_name }}</td>
                                    <td class="text-start">{{ feedback.email }}</td>
                                    <td class="text-start ">{{ feedback.message }}</td>
                                    <td class="text-start"><a href="{% url 'update-feedback' feedback.id %}"
                                                              class="btn btn-outline-secondary">Update</a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        <h3 class="text-center">No Students</h3>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

templates/trainer/list_of_trainers.html
{% extends 'base.html' %}
{% load static %}

{% block title %} List of trainers {% endblock %}

{% block content %}


    <div class="container-fluid col-md-12">
        <div class="row">
            {% for trainer in all_trainers %}
                <div class="col-md-4">
                    <div class="card">
                        {% if trainer.profile %}
                            <img src="{{ trainer.profile.url }}" class="card-img-top" alt="Poza nu exista!">
                        {% else %}
                            <img src="{% static 'images/image_trainer.png' %}" class="card-img-top"
                                 alt="Poza nu exista!">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">
                                {{ trainer.first_name }}
                                {{ trainer.last_name }}</h5>
                            <p class="card-text">
                                {{ trainer.course|upper }} <br>
                                {{ trainer.email }} <br>
                                {{ trainer.department|upper }}
                            </p>
                            {% if perms.trainer.change_trainer or perms.trainer.delete_trainer or perms.trainer.view_trainer %}
                                <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button"
                                        data-bs-toggle="dropdown"
                                        aria-expanded="false">
                                    More actions
                                </button>

                                <ul class="dropdown-menu">
                                {% if perms.trainer.change_trainer %}
                                    <li><a class="dropdown-item" href="{% url 'update-trainer' trainer.id %}">Update</a>
                                    </li>
                                {% endif %}
                                {% if perms.trainer.delete_trainer %}
                                    <li><a class="dropdown-item" href="{% url 'delete-trainer' trainer.id %}">Delete</a>
                                    </li>
                                {% endif %}
                                {% if perms.trainer.view_trainer %}
                                    <li><a class="dropdown-item" href="{% url 'detail-trainer' trainer.id %}">More
                                        Details</a></li>
                                {% endif %}
                            {% else %}
                                <div class="text-center">No actions available!</div>
                            {% endif %}
                            </ul>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

    </div>


{% endblock %}

templates/trainer/update_trainer.html
{% extends 'base.html' %}

{% block title %} Update - {{ trainer }} {% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class='col-md-6 offset-md-3'>
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center"> Update Trainer </h3>
                        <h4 class="text-center"> {{ trainer }}</h4>
                    </div>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="card-body">
                            {{ form }}
                        </div>
                        <div class='card-footer text-center'>
                            <button type="submit" class="btn btn-outline-success">Save</button>
                            <a href="{% url 'list-of-trainers' %}">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}